apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "skysync.fullname" . }}-config
  labels:
    app: {{ template "skysync.name" . }}
    chart: {{ template "skysync.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  logLevel: {{ default "info" .Values.logLevel | quote }}
