apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "skysync.fullname" . }}
  labels:
    app: {{ template "skysync.name" . }}
    chart: {{ template "skysync.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "skysync.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "skysync.name" . }}
        release: {{ .Release.Name }}
    spec:
      serviceAccountName: database-creator
      imagePullSecrets:
        - name: regcred
      initContainers:
        - name: database-creator
          image: index.docker.io/dycsail/database-creator:latest
          args:
            - {{ .Values.tmpDbString }}
      containers:
        - name: skysync
          image: index.docker.io/portalarchitects/skysync:4.6.5.1331
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          ports:
            - containerPort: 9090
              name: skysync
          livenessProbe:
            initialDelaySeconds: 60
            periodSeconds: 60
            timeoutSeconds: 10
            successThreshold: 1
            failureThreshold: 3
            httpGet:
              path: /v1/connections/platforms
              port: skysync
          readinessProbe:
            initialDelaySeconds: 30
            periodSeconds: 20
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
            httpGet:
              path: /v1/connections/platforms
              port: skysync
          resources:
            requests:
              cpu: "1.5"
              memory: "4Gi"
          env:
            - name: SKYSYNC_SERVER__PORT
              value: "9090"
            - name: SKYSYNC_DATA__PROVIDER
              value: sqlserver
            - name: SKYSYNC_DATA__CONNECTION
              valueFrom:
               secretKeyRef:
                 #name: {{ template "skysync.fullname" . }}-secret
                 #key: dbConnectionString
                 name: customer1-connection-string
                 key: connectionString
            - name: ADMIN_PASSWORD
              valueFrom:
               secretKeyRef:
                 name: {{ template "skysync.fullname" . }}-secret
                 key: adminPassword
            - name: SKYSYNC_LOGGING__LEVEL
              valueFrom:
               configMapKeyRef:
                 name: {{ template "skysync.fullname" . }}-config
                 key: logLevel
            - name: SKYSYNC_LICENSE__KEY
              value: {{ .Values.skysyncLicense }}
            - name: SKYSYNC_PERFORMANCE__CONCURRENT_TRANSFERS
              value: "{{ .Values.concurrentTransfers }}"
{{- if .Values.prometheusPushUri }}
            - name: SKYSYNC_METRICS__PROMETHEUS__PUSH_URI
              value: "{{ .Values.prometheusPushUri }}"
{{- end }}
