apiVersion: v1
kind: ConfigMap
metadata:
    name: {{ template "skysync.fullname" . }}-fluentd
    labels:
        app: {{ template "skysync.name" . }}
        chart: {{ template "skysync.chart" . }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
data:
    fluent.conf: |
        <source>
          @type tail
          @id in_tail_container_logs
          path /var/log/containers/{{ template "skysync.fullname" . }}*.log
          pos_file /tmp/{{ template "skysync.fullname" . }}.log.pos
          tag skysync
          read_from_head true
          <parse>
            @type json
            time_format %Y-%m-%dT%H:%M:%S.%NZ
          </parse>
        </source>
        
        <match **>
            #docs: https://github.com/fluent-plugins-nursery/fluent-plugin-cloudwatch-logs
            @type cloudwatch_logs
            region us-west-2
            log_group_name skysync-hosted
            use_tag_as_stream true
            auto_create_stream true
        </match>
