apiVersion: v1
kind: ConfigMap
metadata:
    name: {{ template "skysync.fullname" . }}-fluentd
    labels:
        app: {{ template "skysync.name" . }}
        chart: {{ template "skysync.chart" . }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
data:
    fluent.conf: |
        <source>
          @type tail
          @id in_tail_container_logs
          path /var/log/containers/{{ template "skysync.fullname" . }}*.log
          pos_file /tmp/{{ template "skysync.fullname" . }}.log.pos
          tag skysync
          read_from_head true
          <parse>
            @type json
            time_format %Y-%m-%dT%H:%M:%S.%NZ
          </parse>
        </source>
        
        <match **>
          # docs: https://docs.fluentd.org/v0.12/articles/out_s3
          # note: this configuration relies on the nodes have an IAM instance profile with access to your S3 bucket
          @type s3
          @id out_s3
          @log_level info
          s3_bucket {{ .Values.s3BucketName }}
          s3_region {{ .Values.s3Region }}
          #s3_object_key_format %{path}%Y/%m/%d/cluster-log-%{index}.%{file_extension}
          s3_object_key_format {{ template "skysync.fullname" . }}/%Y/%m/%d/cluster-log-%{index}.%{file_extension}
          <inject>
            time_key time
            tag_key tag
            localtime false
          </inject>
          <buffer>
            @type file
            path /tmp/s3.buffer
            timekey 10m
            timekey_use_utc true
            chunk_limit_size 256m
          </buffer>
        </match>
