apiVersion: v1
kind: Secret
metadata:
  name: {{ template "skysync.fullname" . }}-secret
  labels:
    app: {{ template "skysync.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  adminPassword: {{ required "skysync Password required" .Values.skysyncPassword | b64enc | quote }}
