apiVersion: v1
kind: Secret
metadata:
  name: {{ template "skysync.fullname" . }}-secret
  labels:
    app: {{ template "skysync.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  licenseKey: {{ required "A valid skysyncLicense entry required!" .Values.skysyncLicense | b64enc | quote }}
{{- if .Values.skysyncPassword }}
  adminPassword: {{ .Values.skysyncPassword | b64enc | quote }}
{{- else }}
  adminPassword: {{ printf "!%s*" (randAlphaNum 20) | b64enc | quote }}
{{- end }}
{{- if (index .Values "mssql-linux" "enabled") }}
  dbConnectionString: {{ printf "SERVER=tcp:%s-mssql-linux.%s;DATABASE=SkySyncV4;User ID=sa;Password=%s;" .Release.Name .Release.Namespace (index .Values "mssql-linux" "sapassword") | b64enc | quote }}
{{- else }}
  dbConnectionString: {{ required "A valid dbConnectionString entry required!" .Values.dbConnectionString | b64enc | quote }}
{{- end }}
{{- if .Values.ssl.key }}
{{- if .Values.ssl.password }}
  sslPassword: {{ .Values.ssl.password | b64enc | quote }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "skysync.fullname" . }}-ssl-certs
  labels:
    app: {{ template "skysync.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  ssl-certificate.pfx: {{ .Values.ssl.key | quote }}
{{- end }}
