apiVersion: v1
kind: Service
metadata:
  name: {{ template "skysync.fullname" . }}
  labels:
    app: {{ template "skysync.name" . }}
    chart: {{ template "skysync.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
    - port: 9090
      protocol: TCP
      name: skysync
  selector:
    app: {{ template "skysync.name" . }}
    release: {{ .Release.Name }}
